kind: MutatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1
metadata:
  name: frico-mutating-webhook
webhooks:
  - name: frico-webhook.frico.svc
    sideEffects: None
    admissionReviewVersions:
      - v1
    rules:
      - operations: ["CREATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["pods"]
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFVENDQWZtZ0F3SUJBZ0lVZVd2c1BoMnlsNmhUL2hycVVFWDl2NXdycFl3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01ZV1J0YVhOemFXOXVYMk5oTUNBWERUSTBNREV4TXpFeU1UWXhOMW9ZRHpJeQpPVGN4TURJNE1USXhOakUzV2pBWE1SVXdFd1lEVlFRRERBeGhaRzFwYzNOcGIyNWZZMkV3Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUN6WFk5bUxHV0JzVmVudWNuaWJ5Y0wxQVlXMEFEdHV2aUwKeFk0NFk5b3NVclJ2bnIyUCsyRmIzVGVFSmoyVlQwUjJZcGJLWWpjaHByYUwyS2M4REkreFVMRWVFWTBEME9OWgoxSDNjTS91UisyVUUzbFJrcndhYmc1aHFNZkRHeks0dVFPSXhBdDVTV0xpWTdkeVZSVW00bnR3UDZFT0wxNThEClQzOUhDQnJKdXA1cnpuT2NTbmdienFDbVVYNExVeDRHQXhBVmtuSC9WSmJYQU83eTl1N0ZvY2RsYjY0SC94OHQKcWE5bHN1SEFXWk4wVmpER0ZGdSt2S0t1ajFBdW5vQXg4TjA4RXNWSlEyN3g2dm5XZ0JHVkVxTHUxN1l3T1dVRwpFSDQzUXVLOGRzYy9wRDRUemc1WGE1UnI0MTN0YUFHeFFhU2NYaGxlZ2kra0p6bDEwcENuQWdNQkFBR2pVekJSCk1CMEdBMVVkRGdRV0JCUm9FZ0JKVnMwbE5aZjkwYTYvV3VQOGthMUZ5VEFmQmdOVkhTTUVHREFXZ0JSb0VnQkoKVnMwbE5aZjkwYTYvV3VQOGthMUZ5VEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQQpBNElCQVFDWkFOY2FQZytOd0VHOWY2OWJqemNxdVgvOEJEeEtSamFkU3JmTTVhTlJoS251bDNER2xTQ3FFWEhPCkhsVHo4NHRJUzRPYlEwdnNRa0NQdUpFZU9uWVVvZWlGZ1ZqcDVSUXg5MHZHZHhNKzZRRk1EOTRpRHJTOVYvRjIKbVlPRDlhb0xJdU93dlFnV1c1clRBQ2tJY1hrNHlZeU1tcWgxazV4bU9PNWU2TkZvU1Q2VU4ySWNOZ29zUUJOUQo1NklUYk9DcTdQVk1YcUlsWVY3ZXNGNlp6Znk2aXNBMjZPa1JnNVEwZUIxOWIzZHE0SGw4dHM4QUpoODhFZzczCmJ4bU9MTjNGNGU0YzFLanRaOS9mYURiaEpJMFhheFU1YUNmbzZUYmw5OG94djZZenR3bDBmY2gydnlXaHVaaUEKS2VGRi9aOEhraCs2YUJ3QWdQWlovSHNwVHZxUwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
      service:
        namespace: frico
        name: frico-webhook
        path: /mutate
